const fs = require("fs");

const inicio = new Date("2023-01-01");
const hoje = new Date();
const anos = ((hoje - inicio) / (1000 * 60 * 60 * 24 * 365.25)).toFixed(1);

let readme = fs.readFileSync("README.md", "utf8");
readme = readme.replace(/{{ANOS}}/, anos);

fs.writeFileSync("README.md", readme);
